### ISSUE TITLE
JSON file with all strings

### ISSUE THREAD

**Issue by BroOtti** [CubeCoders/AMPTranslations#4]
Would it be possible to provide a JSON file with all strings? As I only have a network license, I can't get all strings. I also think the existing pull request for german translation was build with a pro license.

**Comment by BroOtti** [comment]
Because of #5 and my own hosted instance of Weblate, I created an en.json file inside my repo https://github.com/BroOtti/AMPTranslations
I don't think it already includes all strings, but it's a beginning :)

**Comment by IceOfWraith** [comment]
Mike shared some secret sauce in a contributors channel. I'll put it here and close this out. I did merge the template file you created as well since I think it's a good base though. This has a lot of other strings that you don't generally get. :)

```
            var messages = {};
            $("body *")
                .contents()
                .filter((_, e) => e.nodeType === Node.TEXT_NODE && e.textContent.match(/[a-zA-Z]\w/) && !e.textContent.contains("<!-- ko"))
                .each(function (_, e) {
                    e.textContent = e.textContent.replace(/^(\s*)([a-zA-Z ].+?)(\s*)$/, function (match, p1, p2, p3) {
                        messages[p2] = p2;
                        return `${p1}${p2}${p3}`
                    });
                });
            console.log(JSON.stringify(messages, null, 4));
```
